/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import model.InvoiceHeader;
import model.InvoiceIteams;
import controller.SIGController;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import model.HeaderTableModel;
import model.ItemsTableModel;

/**
 *
 * @author Abdullah Younis
 */
public class SIGFrame extends javax.swing.JFrame {

    /**
     * Creates new form SIGFrame
     */
    public SIGFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInv = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        btnNewLine = new javax.swing.JButton();
        btnNewLine.addActionListener(listener);
        btnDeleteName = new javax.swing.JButton();
        btnDeleteName.addActionListener(listener);
        btnNewInvoice = new javax.swing.JButton();
        btnNewInvoice.addActionListener(listener);
        btnDeleteInvoice = new javax.swing.JButton();
        btnDeleteInvoice.addActionListener(listener);
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLines = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblInvName = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        lblInvDt = new javax.swing.JLabel();
        lblTotalAmt = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuISave = new javax.swing.JMenuItem();
        menuISave.addActionListener(listener);
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mILoad = new javax.swing.JMenuItem();
        mILoad.addActionListener(listener);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Sales Invoice Generator");

        tblInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInv);

        btnNewLine.setText("Create Item");
        btnNewLine.setPreferredSize(new java.awt.Dimension(85, 23));

        btnDeleteName.setText("Delete Item");
        btnDeleteName.setName(""); // NOI18N

        btnNewInvoice.setText("New Invoice");
        btnNewInvoice.setPreferredSize(new java.awt.Dimension(85, 23));

        btnDeleteInvoice.setText("Delete Invoice");
        btnDeleteInvoice.setPreferredSize(new java.awt.Dimension(85, 23));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnDeleteInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(btnNewLine, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnDeleteName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNewInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeleteName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewLine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnDeleteName.getAccessibleContext().setAccessibleName("btnDeleteLine");

        tblLines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblLines);

        jLabel2.setText("Invoice Name:");

        jLabel3.setText("Customer Name:");

        jLabel4.setText("Invoice Date:");

        jLabel5.setText("Invoice Total:");

        lblInvName.setText(".");

        lblCustName.setText(".");

        lblInvDt.setText(".");

        lblTotalAmt.setText(".");

        jMenu1.setText("File");

        menuISave.setText("Save");
        jMenu1.add(menuISave);
        jMenu1.add(jSeparator1);

        mILoad.setText("Load");
        jMenu1.add(mILoad);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)
                                        .addComponent(lblInvName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblInvDt)))
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotalAmt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCustName)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(lblInvName)
                            .addComponent(lblCustName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(lblInvDt)
                            .addComponent(lblTotalAmt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteInvoice;
    private javax.swing.JButton btnDeleteName;
    private javax.swing.JButton btnNewInvoice;
    private javax.swing.JButton btnNewLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblInvDt;
    private javax.swing.JLabel lblInvName;
    private javax.swing.JLabel lblTotalAmt;
    private javax.swing.JMenuItem mILoad;
    private javax.swing.JMenuItem menuISave;
    private java.awt.Panel panel1;
    private javax.swing.JTable tblInv;
    private javax.swing.JTable tblLines;
    // End of variables declaration//GEN-END:variables

    
    // Owen code not generated
    public static DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    private SIGController listener = new SIGController(this);
    private HeaderTableModel hTblModels; // for header
    private ItemsTableModel  iTblModels; // for invoice
    private ArrayList<InvoiceHeader> AllInvoices;
    private ArrayList<InvoiceIteams> AllInvoicesItems;
    
    public ArrayList<InvoiceHeader> getInvoiceDetails()
    {
        if(AllInvoices == null)
            AllInvoices = new ArrayList<>();
        return AllInvoices;
    }
            
    public HeaderTableModel getInvoicesTableModelDetails()
     {
        if (hTblModels == null)
        {
            hTblModels = new HeaderTableModel(getInvoiceDetails());
        }
        return hTblModels;
    }
     
     
    public ArrayList<InvoiceIteams> getIteamDetails()
    {
        if(AllInvoicesItems == null)
            AllInvoicesItems = new ArrayList<>();
        return AllInvoicesItems;
    }
     
    
    public void setInvoiceDetails(ArrayList<InvoiceHeader> invoices) 
     {
        this.AllInvoices = invoices;
     }
    
    public ItemsTableModel getInviceItemTbMod()
    {
        return iTblModels;
    }
    
    public void setInviceItemTbMod(ItemsTableModel iTblModels)
    {
        this.iTblModels = iTblModels;
        tblLines.setModel(iTblModels);
    }
    
    
  
    public InvoiceHeader getInvByNumber(int iNumber)
    {
        InvoiceHeader invoice = null;
        for(InvoiceHeader item: getInvoiceDetails())
        {
            if(item.getNumber() == iNumber)
                invoice = item;
                break;
        }
        return invoice;
    }
    
    public InvoiceHeader getInvByNumber2(int iNumber)
     {
        for (InvoiceHeader item : getInvoiceDetails()) 
        {
            if (item.getNumber() == iNumber) 
            {
                return item;
            }
        }
        return null;
     }
     
    public SIGController getController()
     {
         return listener;
     }
     
     
     // Create setter to use it from Controller
     public void setHTblModel(HeaderTableModel headerTableModel) 
     {
        this.hTblModels = headerTableModel;
        this.tblInv.setModel(headerTableModel);
     }
     
      
     public void setLTblModel(ItemsTableModel itemsTableModel) 
     {
        this.iTblModels = itemsTableModel;
        this.tblLines.setModel(itemsTableModel);
     }
     
     
    public JTable getInvoiceTableDetails() 
    {
        return tblInv;
    }
    
    
    public JTable getItemTableDetails() 
    {
        return tblLines;
    }
    
  
            

}
